config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show] do
    resources :bookings, only: [:show, :index]
  end
  resources :planets do
    resources :bookings do
      member do
        patch :accept
      end
    end
  end
  resources :planets do
    resources :booking, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, :end_date, presence: true
  belongs_to :planet
  belongs_to :user

  # validates :not_overlapping_another_booking
  # def booking_overlap
  #     Booking.where(planet_id: self.planet_id)
  #     Booking.where.not(id: self.id)
  #     Booking.where.not(
  #       ‘arrival_date >= :departure_date
  #        OR
  #        departure_date <= :arrival_date’,
  #           arrival_date: arrival_date, departure_date: departure_date
  #           )
  #   end
  # def not_overlapping_another_booking
  #   unless booking_overlap.empty?
  #     errors[:base] <<
  #       ‘This Booking is conflicting with another Booking’
  #   end
  # end
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :name, :size, :distance_from_sun, :price_per_day, presence: true
  validates_uniqueness_of :name, on: :create, message: "must be unique"
  validates :size, :distance_from_sun, :price_per_day, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :planets, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_user, only: :show
  before_action :find_planet, only: [:new, :create, :show, :accept]
  before_action :find_booking, only: [:edit, :update, :show, :destroy, :accept]

  def index
    @bookings = Booking.all
    @user = current_user
  end

  def show
  end

  def new
    @user = current_user
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.planet = @planet
    @booking.user = @user
    if @booking.save
      @booking.save!
      redirect_to user_bookings_path(@user)
    else
      render "form"
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      flash[:success] = "Your booking was successfully updated"
      redirect_to booking_path(@booking)
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @booking.destroy
      flash[:success] = "Your booking has been deleted"
      redirect_to bookings_path
    else
      flash[:error] = "Something went wrong"
      redirect_to bookings_path
    end
  end

  def accept
    @booking.update(status: true)
    @booking.save!
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :message)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_planet
    @planet = Planet.find(params[:planet_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :find_planet, only: [:edit, :update, :show, :destroy]
  def index
    @planets = Planet.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @user = current_user
    @planet = Planet.new
  end

  def create
    @user = current_user
    @planet = Planet.new(planet_params)
    @planet.user = @user
    if @planet.save
      @planet.save!
      redirect_to planet_path(@planet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @planet.update(planet_params)
      flash[:success] = "Object was successfully updated"
      redirect_to planet_path(@planet)
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @planet.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to planets_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to planets_path
    end
  end

  private

  def find_planet
    @planet = Planet.find(params[:id])
  end

  def planet_params
    params.require(:planet).permit(:name, :size, :distance_from_sun, :price_per_day, :photo, :description, :has_oxygen, :has_wifi, :inhabited, :has_starbucks, :has_water)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="container">
  <div id="new-booking-container">
    <div class="new-booking-title">
      <h2 class="new-booking-title">Your booking request</h2>
    </div>
    <%= simple_form_for [@planet, @booking] do |f| %>
      <%= f.input :start_date, as: :string, input_html: { class: "datepicker"}, label_html: { class: 'labels' } %>
      <%= f.input :end_date, as: :string, input_html: { class: "datepicker" }, label_html: { class: 'labels' } %>
      <%= f.input :message, label_html: { class: 'labels' } %>
      <div class="buttons">
        <%= f.button :submit, "Submit booking request", class: "btn btn-success btn-lg" %>
        <div class="cancel-btn" style="margin-top: 10px;">
          <%= link_to "Cancel", planet_path, class: "btn btn-secondary js-close-button", id: "cancel-button" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/accept.js.erb
$('.status-msg').text("<%= booking.status %>");

app/views/bookings/index.html.erb
<div class="bookings-index-background">
  <div class="container">
    <h1 class="your-bookings-header">Your Bookings</h1>
    <ul class="booking-list">
      <% @bookings.sort.each do |booking| %>
        <% if booking.user_id == @user.id %>
          <li class="booking-info">
            <div class="booking-flex-box">
              <div class="planet-info-left">
                <%# logic for getting the planet name of the booking %>
                <div class="planet-name">
                  <% planet = Planet.where(id: booking.planet_id) %>
                  <% planet_name = Planet.where(id: planet[0].id) %>
                  <h3 class="planet-name"><strong>Booking for your trip to: <%= planet_name[0].name %></strong></h3>
                </div>
                <div class="booking-dates">
                  <ul>
                    <li class="booking-start-date-list">
                      <p class="booking-start-date-text"><strong>Start date:</strong> <%= booking.start_date.day %>/<%= booking.start_date.month %>/<%= booking.start_date.year %></p>
                    </li>
                    <li class="booking-end-date-list">
                      <p class="booking-end-date-text"><strong>End date:</strong> <%= booking.end_date.day %>/<%= booking.end_date.month %>/<%= booking.end_date.year %></p>
                    </li>
                    <li class="booking-total-days-list">
                      <p class="booking-total-days-text"><strong>Total visit time:</strong> <% total_dates = booking.end_date - booking.start_date %><%= total_dates.to_i %> days</p>
                    </li>
                    <li class="booking-total-price-list">
                      <p class="booking-total-price-text"><strong>Total price of trip: </strong>£<%= total_dates.to_i * planet[0].price_per_day%></p>
                    </li>
                  </ul>
                </div>
                <div class="status-info">
                  <div class="status-msg">
                    <% if booking.status %>
                      <p class="booking-accepted">Booking accepted</p>
                    <% else %>
                      <p class="booking-not-yet-accepted">Booking not yet accepted</p>
                    <% end %>
                  </div>
                  <%# ############################ To be implemented in second week ########################### %>
                  <%# if !booking.status %>
                    <%#= link_to accept_planet_booking_path(@planet, booking), method: :patch, remote: true do %>
                      <%# <button class="btn btn-primary accept-booking-request">Accept booking request</button> %>
                    <%# end %>
                  <%# else %>
                    <%# <button class="btn btn-primary disabled-btn" disabled = true>Booking accepted</button> %>
                  <%# end %>
                  <%# ######################################################################################## %>
                </div>
              </div>
              <div class="planet-info-right">
                <div class="planet-name">
                  <% planet = Planet.where(id: booking.planet_id) %>
                  <% planet_name = Planet.where(id: planet[0].id) %>
                  <div class="planet-image">
                    <img src="<%= cl_image_path planet_name[0].photo.key %>" class="planet-img">
                  </div>
                </div>
              </div>
            </div>
          </li>
          <% else %>
          <p class="no-bookings">No bookings</p>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="planet-name">
    <h2>Your booking for: <%= @planet.name %></h2>
  </div>
  <div class="dates">
    <div class="start-date">
      <strong>Start date:</strong> <%= @booking.start_date %>
    </div>
    <div class="end-date">
      <strong>End Date:</strong> <%= @booking.end_date %>
    </div>
  </div>
  <br>
  <br>
  <div class="status-btn">
    <div class="status-msg">
      <% if !@booking.status %>
        <h3 class="booking-not-yet-accepted">Booking not yet accepted</h3>
      <% else %>
        <h3 class="booking-accepted">Booking accepted</h3>
      <% end %>
    </div>
    <br>
    <br>
    <%= link_to planet_booking_path(@planet, @booking) do %>
      <button class="btn btn-primary">Accept booking request</button>
    <% end %>
    <%# if statement to check current_user against planet.user_id %>
    <%# if match then show the current_user's planet bookings only %>
    <%# if the 'status' column is false on a booking, then the button is shown, and change the status on the view to 'not yet accepted' %>
    <%# else if the 'status' column is true, then make the button unclickable, and change the status on the view to 'accepted'  %>
  </div>
  <br>
  <div class="return-to-bookings-index btn btn-primary">
    <%= link_to "Return to Bookings Page", planet_bookings_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BEYONDRentals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/planets/edit.html.erb
<div class="container">
  <div class="col-sm-6 offset-sm-3 mt-3 mb-3">
    <h1><strong>Create a planet</strong></h1>
    <div class="edit-planet-form">
      <%= simple_form_for (@planet) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :size, placeholder: 'Radius in km'%>
      <%= f.input :distance_from_sun, placeholder: 'Distance in million km' %>
      <%= f.input :price_per_day %>
      <div class="d-flex justify-content-between flex-wrap">
        <%= f.input :inhabited %>
        <%= f.input :has_oxygen, label: "Oxygen" %>
        <%= f.input :has_wifi, label: "Wifi" %>
        <%= f.input :has_water, label: "Water" %>
        <%= f.input :has_starbucks, label: "Starbucks" %>
      </div>
      <%= f.input :photo, label: "Image", as: :file %>
      <%= f.submit "Update Planet", class: "btn btn-dark btn-block" %>
  </div>
  <% end %>
  </div>

</div>

app/views/planets/index.html.erb
<body style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1597329943/stars_kgzgyj.png);">
  <div id="planets-gallery" class="container">
    <div class="d-flex justify-content-between flex-wrap">
    <% if @planets.any? %>
        <% @planets.each do |planet| %>
          <% if planet.photo.attached? %>
            <%= link_to planet_path(planet)  do %>
              <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path planet.photo.key %>)">
                <h1><%= planet.name %></h1>
              </div>
            <% end  %>
          <% else %>
            <%= link_to planet_path(planet)  do %>
              <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.pngitem.com/pimgs/m/32-327361_planet-saturn-saturn-planet-drawing-hd-png-download.png)">
                <h1><%= planet.name %></h1>
              </div>
            <% end  %>
          <% end %>
        <% end %>
    <% else %>
      <h3>There are no planets, please check back later for any new listings.</h3>
    <% end %>
    </div>
  </div>
</body>

app/views/planets/new.html.erb
<div class="container">
  <div class="col-sm-6 offset-sm-3 mt-3 mb-3">
    <h1><strong>Create a planet</strong></h1>
    <div class="new-planet-form">
      <%= simple_form_for (@planet) do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :size, placeholder: 'Radius in km'%>
      <%= f.input :distance_from_sun, placeholder: 'Distance in million km' %>
      <%= f.input :price_per_day %>
      <div class="d-flex justify-content-between flex-wrap">
        <%= f.input :inhabited %>
        <%= f.input :has_oxygen, label: "Oxygen" %>
        <%= f.input :has_wifi, label: "Wifi" %>
        <%= f.input :has_water, label: "Water" %>
        <%= f.input :has_starbucks, label: "Starbucks" %>
      </div>
      <%= f.input :photo, label: "Image", as: :file %>
      <%= f.submit "Create Planet", class: "btn btn-dark btn-block" %>
  </div>
  <% end %>
  </div>

</div>

app/views/planets/show.html.erb
<% if @planet.photo.attached? %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @planet.photo.key %>)">
      <h1><%= @planet.name %></h1>
  </div>
<% else %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.pngitem.com/pimgs/m/32-327361_planet-saturn-saturn-planet-drawing-hd-png-download.png)">
      <h1><%= @planet.name %></h1>
  </div>
<% end %>
<div class="container">
  <div class= "mt-4">
    <%= @planet.description %>
  </div>
  <div class="row mt-4">
    <div class="col-sm-8">
      <ul id="planet-attr-list">
        <li>
          <strong>Size:</strong> <%= @planet.size %> km
        </li>
        <li>
          <strong>Distance from Sun:</strong> <%= @planet.distance_from_sun %> million km
        </li>
        <li>
          <strong>Price per day:</strong> £<%= @planet.price_per_day %>
        </li>
      </ul>
    </div>
    <div id="planet-attr-icons" class="col-sm-4">
      <p style="text-align: center; margin: 16px;"><strong>Amenities</strong></p>
      <ul style="list-style: none">
      <% if @planet.inhabited %>
        <li style="text-align: center">
          <i class="fas fa-users" style="color: #167ffb; " title="Is inhabited"></i>
          <p style="color: #167ffb">Inhabited</p>
        </li>
      <% else %>
        <li style="text-align: center">
          <i class="fas fa-users" style="color: grey; opacity: 0.2;" title="Is not inhabited"></i>
          <p style="opacity: 0.2;">Inhabited</p>
        </li>
      <% end %>
        <% if @planet.has_oxygen %>
        <li style="text-align: center">
          <i class="fas fa-lungs" style="color: #167ffb;" title="Has oxygen"></i>
          <p style="color: #167ffb">Oxygen</p>
        </li>
      <% else %>
        <li style="text-align: center">
          <i class="fas fa-lungs" style="color: grey; opacity: 0.2;" title="Does not have oxygen"></i>
          <p style="opacity: 0.2;">Oxygen</p>
        </li>
      <% end %>
        <% if @planet.has_water %>
        <li style="text-align: center">
          <i class="fas fa-tint" style="color: #167ffb;" title="Has water"></i>
          <p style="color: #167ffb">Water</p>
        </li>
      <% else %>
        <li style="text-align: center">
          <i class="fas fa-tint" style="color: grey; opacity: 0.2;" title="Does not have water"></i>
          <p style="opacity: 0.2;">Water</p>
        </li>
      <% end %>
        <% if @planet.has_wifi %>
        <li style="text-align: center">
          <i class="fas fa-wifi" style="color: #167ffb;" title="Has WiFi"></i>
          <p style="color: #167ffb"> Wifi</p>
        </li>
      <% else %>
        <li style="text-align: center">
          <i class="fas fa-wifi" style="color: grey; opacity: 0.2;" title="Does not have WiFi"></i>
          <p style="opacity: 0.2;">Wifi</p>
        </li>
      <% end %>
      <% if @planet.has_starbucks %>
        <li style="text-align: center">
          <i class="fas fa-coffee" style="color: #167ffb;" title="Has Starbucks"></i>
          <p style="color: #167ffb">Starbucks</p>
        </li>
      <% else %>
        <li style="text-align: center">
          <i class="fas fa-coffee" style="color: grey; opacity: 0.2;" title="Does not have Starbucks"></i>
          <p style="opacity: 0.2;">Starbucks</p>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
  <% if current_user.id == @planet.user_id %>
    <div class="owner-links">
      <%= link_to "Back to base", planets_path, class: "btn btn-primary" %>
      <br>
      <br>
      <%= link_to "Edit this planet", edit_planet_path(@planet), class: "btn btn-secondary" %>
      <br>
      <br>
      <%= link_to planet_path(@planet), method: :delete, data: { confirm: "Charging the Death Star... Fire?" } do %>
        <i class="fas fa-bomb"></i> Exterminate
      <% end %>
      <br>
    </div>
  <% else %>
    <div class="renter-links">
      <div class="drawer-btn">
        <button class="btn btn-primary js-open-button">Make a booking</button>
      </div>
      <div class="Drawer js-drawer" hidden>
        <div class="container" id="render-container">
          <%= render "bookings/new", planet: @planet, booking: @booking %>
        </div>
      </div>
      <br>
      <%= link_to "Back to base", planets_path, class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <p>BEYOND RENTALS</p>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a planet", new_planet_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%= link_to "Booking requests", user_bookings_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://pbs.twimg.com/profile_images/1221986795786817536/7uo7pwSp_400x400.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item" style="font-size: 14px;" ><%= current_user.email %></p>
            <%= link_to "Planets", planets_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
index.html.erb

app/views/users/new.html.erb
new.html.erb

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="center">
      <%= image_tag avatar_url(@user), class: "avatar-full"%>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Verification</div>
      <div class="panel-body">
        Email</br>
        Phone number
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>